name: "Build (git + daily + no rechunk)"

on:
  schedule:
    - cron: "30 04 * * *" # 04:30 UTC everyday
  push:
    paths:
      - "files/**"
      - "modules/**"
      - "recipes/**"
      - "cosign.pub"
      - ".github/workflows/build-git*.yml"
    branches-ignore:
      - "dependabot**"
      - "compiler"
  pull_request:
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          # - images/hyprland/41/hyprland--41-git-daily.yml
          - images/cosmic/42/cosmic--41-git-daily.yml
          - images/plasma/41/plasma--41-git-daily.yml
          - images/plasma/42/plasma--42-git-daily.yml
          - images/gnome/41/gnome--41-git-daily.yml
          - images/gnome/42/gnome--42-git-daily.yml
          - images/xfce/41/xfce--41-git-daily.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
